/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TeamsImport } from './routes/teams'
import { Route as PlayersImport } from './routes/players'
import { Route as GeneratedTeamImport } from './routes/generated-team'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const TeamsRoute = TeamsImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRoute,
} as any)

const PlayersRoute = PlayersImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => rootRoute,
} as any)

const GeneratedTeamRoute = GeneratedTeamImport.update({
  id: '/generated-team',
  path: '/generated-team',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/generated-team': {
      id: '/generated-team'
      path: '/generated-team'
      fullPath: '/generated-team'
      preLoaderRoute: typeof GeneratedTeamImport
      parentRoute: typeof rootRoute
    }
    '/players': {
      id: '/players'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof PlayersImport
      parentRoute: typeof rootRoute
    }
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/generated-team': typeof GeneratedTeamRoute
  '/players': typeof PlayersRoute
  '/teams': typeof TeamsRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/generated-team': typeof GeneratedTeamRoute
  '/players': typeof PlayersRoute
  '/teams': typeof TeamsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/generated-team': typeof GeneratedTeamRoute
  '/players': typeof PlayersRoute
  '/teams': typeof TeamsRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/generated-team' | '/players' | '/teams'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/generated-team' | '/players' | '/teams'
  id: '__root__' | '/' | '/generated-team' | '/players' | '/teams'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GeneratedTeamRoute: typeof GeneratedTeamRoute
  PlayersRoute: typeof PlayersRoute
  TeamsRoute: typeof TeamsRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GeneratedTeamRoute: GeneratedTeamRoute,
  PlayersRoute: PlayersRoute,
  TeamsRoute: TeamsRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/generated-team",
        "/players",
        "/teams"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/generated-team": {
      "filePath": "generated-team.tsx"
    },
    "/players": {
      "filePath": "players.tsx"
    },
    "/teams": {
      "filePath": "teams.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
